### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joeynq** [joeynq/vermi#7]
Roadmap

This ticket to track the expected feature of Vermi

[x] Vermi core application
- [x] Vermi life-cycle
- [x] Consistent module developement interface
- [x] Run directly with Bun.server API
- [x] Has dependency injection solution (use `awilix`)
- [x] Hook to life cycle
- [x] Built-in Logger (use `console`)
- [x] Static files
- [x] Use separated context (use `AsyncLocalStorage`)

[ ] Vermi Files
- [ ] File upload
- [ ] File compression and conversion
- [ ] Cache
- [ ] Download (stream, resumable)
- [ ] File size validation
- [ ] Metadata validation

[ ] Custom Logger
- [x] Pino (recommended)
- [x] Consola
- [ ] Log4js
- [ ] Winston
- [ ] LogLevel

[x] Vermi Router
- [x] Decorator-based controller, method and handler parameters
- [x] Decorator-based middlewares
- [x] Router's request life-cycle
- [x] Fast and OpenAPI-compatible payload schema (use `typebox`)
- [x] Fast query string parser (use `fast-querystring`)
- [x] Fast built-in validator (use `typebox-validator`)
- [x] Fast route matcher (use `memorist`)
- [x] Standard Http method and error response
- [ ] Allow extends to another schema and validator
  - [ ] `ajv`
  - [ ] `zod`
- [-] Express' middlewares compatible (not tested yet)
- [ ] OpenAPI-compatible routes data
- [x] Customize response handler
- [x] Customize error handler

[ ] Vermi REST (Rest api specific features for Router)

[ ] Vermi Event: emit, subscribe to event
- [ ] Use separated context (use `AsyncLocalStorage`)
- [ ] Decorator-based event handler
- [ ] Decorator-based event trigger
- [ ] Schedule Event
- [ ] Webhook Event (use `Vermi Router`)
- [ ] Event stores
  - [ ] Local (using `mitt`)
  - [ ] DragonFly pub/sub

[ ] Vermi Authorization (module and router middleware)
- [x] Bearer
- [x] Basic
- [ ] Digest

[x] Rate-limter (use `rate-limiter-flexible`)

[ ] Security
- [x] CORS
- [x] Helmet
- [ ] CSRF
- [ ] Recaptcha

[ ] OpenAPI
- [ ] Generate specification file (`openapi.yml`)
- [ ] Document UI (use `scalar`)

[ ] GraphQL
- [ ] GraphQL Server
  - [x] Yoga
  - [ ] Apollo
- [ ] GraphQL Federation supports

[ ] Notification
- [x] Using Worker
- [x] React template rendering (use `react-email`)
- [x] Email sending SMTP (use `nodemailer`)
- [ ] SMS
  - [ ] Twilio
  - [ ] Amazon SNS
- [ ] Push
  - [ ] Amazon SNS
  - [ ] FCM
  - [ ] APN
- [ ] Websocket

[ ] Vermi CLI
- [ ] Create app from scratch
- [ ] Create module
- [ ] Cli extension (no description yet)

[ ] WebSockets
- [ ] Decorator-based Websocket Controller
- [ ] One-to-One mode (one socket, one namespaces)
- [ ] One-to-Many mode (one socket, multiple namespaces)
- [ ] Authorization
- [ ] Client API

[ ] Database
- [x] MikroORM
- [ ] TypeORM
- [ ] Sequelize
- [ ] Mongoose
- [ ] Dazzle

[ ] Business logic support (DDD)
- [ ] DTO Mapper
- [ ] Base service, Entity, Repository interface

[ ] Sidejob
- [x] NPM store
- [ ] Publish using Github Action
- [ ] Document pages
  - [ ] Writing
  - [ ] Deploy (use `Docsaurus` and `Vercel`)
- [ ] Readme.md
- [ ] Unit testing
